modmail/modmail.py

Preview:
How does this looks in message _(this is a single message sent from mobile client)_:

[Modmail] Better attachments embedding

---

highlight/highlight.py

Make highlight DM header and embed one message

---

unbelievaboat/unbelievaboat.py

Adds in the checks for embed links permissions on the work, crime, rob and settings commands

[unbelievaboat] check for proper perms for some commands

---

r6/__init__.py
r6/info.json
r6/r6.py
r6/stats.py

Update R6 to use my r6statsapi library and 3.2 changes.

Convert R6 cog to use r6statsapi lib + 3.2/3.1 backwards compat

---

r6/r6.py

[r6] 1.4.2

---

commandstats/commandstats.py

*Not tested/formatted, written "on the go" on github*

[CommandStats] add support for another guild's command stats

---

unbelievaboat/wallet.py

Before this change, this wasn't changing wallet balance properly.

[Unbelievaboat] Fix depositing

---

redditpost/redditpost.py

On `[p]redditpost add` config key is set to "webhooks", but not at the places where it was called.

[RedditPost] Fix webhooks config key

---

dankmemer/README.md

I hope you won't mind this! Feel free to merge or reject. 👍

made the installation and setup instructions more detailed

---

userinfo/userinfo.py

I kinda hard coded the emoji raw values, I hope that's okay. Feel free to close this PR if you think this is a wrong way.
I'm still a baby learning python. Trying my best. :okcat:

Added support for new status emojis! :yay:

---

userinfo/userinfo.py

Preda updated the old :mobile: emoji with the better quality one just now upon my request, so the emoji ID changed.
So I thought I would better PR new emoji ID to fix in the cog. Sorry for any inconvenience. 🙏

updating new emoji ID for :mobile: emoji

---

botlistspost/botlistspost.py

https://docs.server-discord.com

[botlistspost] add support for "SDC" list

---

userinfo/userinfo.py

I know it's small and pointless, but I just HAD to make the PR

Fix a typo in comment for red user data funcs

---

simleague/simset.py

**SimLeague**
* Added option to show esultchannels with `[p]simset resultchannels show`
* Added option to clear resultchannels with `[p]simset resultchannels  clear`
* Added duplicate channel check when trying to add a new result channel

Improve simset resultchannel

---

stickbugged/converters.py
stickbugged/stickbugged.py

This uses the single class of stickbug and closes the video files once writing to help with memory issues. This also uses a history search for images and emojis as well.

[Stickbugged] Some minor fixes to the stickbug cog

---

verify/verify.py

Users will be greeted in # general (and mods will also be notified)

Added welcome greetings to verify.py

---

verify/verify.py

Persistent storage added for welcome_messages list, new command "addwelcomemsg" added.

Updated verify.py

---

unbelievaboat/wallet.py

Fixes wallet not depositing all when global bank is on.

[unebelievaboat] wallet all deposit

---

forward/forward.py

Adds the option to blacklist users from receiving their forwarded dms.

[forward] blacklist

---

redditpost/redditpost.py

Link to regex101 with the regex I used: https://regex101.com/r/SOJjWZ/4
Sanitizes subreddit inputs from a variety of formats.

Sanitize user subreddit input

---

redditpost/redditpost.py

because Trusty pinged me about it in #testing 
I didn't really care to validate the names client-side, so I didn't bother in #66, but if I got a ping about it...
https://regex101.com/r/SOJjWZ/5

validate subreddit names too

---

tips/tips.py

change default to true

---

tips/tips.py

Adds support for customization of tip message formatting and also makes the cog work with any version of discord.py.

[tips] Custom formatting support

---

embedcreator/utils.py

I believe this is also needed, given the error in the cog support server

[EmbedCreator] json module for utils

---

commandstats/info.json

[CommandStats] fix a typo

---

connect4/connect4.py

Fixes an indentation typo with player ids for stats.

[connect4] indent typo

---

botlistspost/botlistspost.py

[Botlistpost] Fixes for prefixes

---

unbelievaboat/roulette.py

I have not tested this change, though I don't expect anything to break here.

Save the bet only *after* withdrawing succeeds

---

snipe/snipe.py

Adds a guild only check to `[p]snipe` and also changes the listener to use on_message_delete.

[Snipe] guild only check

---

connect4/connect4.py
connect4/core.py

Updates the cog to use a menu class to make exception handling and post-game cleanup handling easier to manage.
Also adds a stats command.
Not all edge cases have been tested.
Related traceback:
```
File "/home/phen/noumenon-core/.venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
File "/home/phen/noumenon/cogs/CogManager/cogs/connect4/connect4.py", line 81, in connect4
await self.end_game(game, message)
File "/home/phen/noumenon/cogs/CogManager/cogs/connect4/connect4.py", line 120, in end_game
await message.edit(content=str(game))
File "/home/phen/noumenon-core/.venv/lib/python3.8/site-packages/discord/message.py", line 1111, in edit
data = await …
```

[Connect4] menus

---

highlight/highlight.py

Argument is spelt as "argument" and not "arguement" :)

[Highlight] Fix various argument typos

---

antispam/info.json
apitools/info.json
botlistspost/info.json
commandstats/info.json
covid/info.json
crypto/info.json
dankmemer/info.json
dminvites/info.json
embedcreator/info.json
embedcreator/test.json
f1/info.json
faceit/info.json
forward/info.json
highlight/info.json
info.json
joinmessage/info.json
jsk/info.json
mod/info.json
news/info.json
r6/info.json
redditpost/info.json
serverlock/info.json
simleague/info.json
snipe/info.json
snipe/snipe.py
stickbugged/info.json
tips/info.json
unbelievaboat/info.json
userinfo/info.json

I could have just told pagify to do 1024 chars so it would fit in the embed field, but I thought now that discord has upped the embed description limit to 4000 it would be better to just put it there.
Fixes: https://sentry.io/share/issue/49da8a16971240308ef2baea22333855/

[Snipe] Fix over 1024 chars

---

snipe/snipe.py

Fixes the channel typo in snipe cog

[Snipe] fix typo

---

giveaways/giveaways.py

https://sentry.io/share/issue/4fc9775e76d84d2cb40f623725a1dd23/

[Giveaways] Fix giveaway end message when there's more than 1 winner

---

f1/__init__.py
f1/f1.py
f1/info.json
jsk/__init__.py
jsk/info.json
redditpost/__init__.py
redditpost/info.json
redditpost/redditpost.py
unbelievaboat/__init__.py
unbelievaboat/info.json
unbelievaboat/unbelievaboat.py

- Redditpost
- Unbelievaboat
- F1
- jsk
Redditpost has been tested for some days to ensure it actually worked 100% and posted as it should and it does what it should as before and now.
- Buttons is removed as they no longer work on 2.0 without changing them to work on 2.0. 
- i added back your old way that you had before buttons. 
- The command `[p]redditpost imageonly` that you added with buttons still work on 2.0 as well.

Support for discord.py 2.0

---

highlight/highlight.py

I see there weren't any checks if the highlighted user is blacklisted or not, so this will check if the highlighted user is blacklisted from the bot or not.

Make highlight will only be sent if user isn't blacklisted

---

palette/palette.py

I also fixed another command that I forgot to add amount < 1 handler

Fix hex not showing on `[p]hexpalette`

---

crypto/crypto.py

This code allows a user input on !crypto list command, and shows their balance of various coins.
Solves issue 168:
https://github.com/flaree/flare-cogs/issues/168

Can check other user's bitcoin balances.

---

giveaways/giveaways.py

i think this works ?
i didn't test the second commit but i think deleting the message would also cause this too

fix endless spam for ending giveaway when bot cant send message in channel 

---

highlight/highlight.py

Updated highlight guild command.

---

trigger/objects.py
trigger/trigger.py

- Cleanup leftover print in my last PR
- Add on_mesage_edit listener only processing if embeds are being searched. This was due to a bug where Auto URL Embeds are edited in after instead of on_message.

Cleanup Unnecessary Print and Fix Auto URL Embeds

---

trigger/trigger.py

- Update to slightly more convoluted `on_raw_message_edit` as it can use a cached version of the original message unlike `on_message_edit`. Believe this to be more appropriate especially as we don't even use the original message.

Update to more appropriate on_raw_message_edit

---

tips/info.json

Feel free to choose one of these if you don't want both, I'm just hoping to get rid of the old username references :)

Update reference to myself in the cog install message

---

giveaways/converter.py

This fixes the blacklist of the giveaway so it is not empty.
Fixes #225

[Giveaway] Fix Blacklist not being set empty

---

tiktokreposter/tiktokreposter.py

Resolves heartbeat issues reported from [here](https://discord.com/channels/240154543684321280/736337036067209216/1252615375842181171) by offloading the full video download and conversion into a thread executor, rather than only the conversion

[TikTokReposter] Offload all i/o to thread

---

palette/palette.py

basically supports any url if its content type starts with "image/"

[Palette] Support more image types

---

f1/f1.py

context: https://discord.com/channels/240154543684321280/736337036067209216/1354105989212799048 
works on my testing just now

updates the api url for the F1 cog 
