- highlight/highlight.py
Added the f for an f-string that didn't have it, removed an extra period, and added a check if the message was in DM, to ignore it before querying Config.
> F-string + avoid unneeded config call in DM

- unbelievaboat/unbelievaboat.py
Unbelievaboat the bot does it this way where it will convert a negative value to a positive one. Currently there's an exception in wallet deposit if you use a negative value, which this resolves:
```
File "/.../lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
File "/.../Red-DiscordBot/cogs/CogManager/cogs/unbelievaboat/unbelievaboat.py", line 649, in deposit
await self.bankdeposit(ctx, ctx.author, amount)
File "/.../Red-DiscordBot/cogs/CogManager/cogs/unbelievaboat/unbelievaboat.py", line 115, in bankdeposit
await bank.deposit_credits(user, amount)
File "/.../lib/python3.7/site-packages/redbot/core/bank.py", line 279, in deposit_credits
raise ValueError("Invalid deposit amount {} <= …
```
> [Unbelievaboat] Handle negatives in wallet deposit

- forward/forward.py
- forward/info.json
- Add the possibility to receive the notifications to a specified channel instead of bot owner DMs.
- Use `.to_dict()` method to get embed data if they exist instead of set everything manually.
- Add the possibility to mention a member when using `[p]pm` command.
> [Forward] Adds channel notifications instead of bot owner DMs + little changes

- unbelievaboat/unbelievaboat.py
* Usage display needed an additional `>`
* set-wallet's on_or_off wasn't a bool before so it never could qualify as disabled
* Settings display changed to show appropriate set-wallet value
> [Unbelievaboat] Fix set-wallet command

- commandstats/commandstats.py
This PR supports receiving events from third-party cogs to log as if they were commands. This is useful for counting user interactions with the bot via reaction buttons or any other action that is not itself a command.
The interface is pretty simple: the cog should just dispatch the custom event `commandstats_action` with ctx as its argument. See:
https://github.com/synrg/dronefly/issues/96
The simplest case of inatcog's use of this interface is here:
https://github.com/synrg/dronefly/blob/af71063d0760cd7fe33f26289b024db9b890b488/inatcog/listeners.py#L92-L95
The `on_message_without_command()` handler treats the user's message as if it were a command to automatically preview a link pasted into the channel. Because it's in an `on` handler, it synthesizes `ctx` with enough of the Context to …
> Log actions from third-party cogs as commands.

- redditpost/redditpost.py
This is to avoid the task die in case of an exception.
> [RedditPost] Handle errors in bg_loop

- covid/covid.py
This fixes the issue when value for "Critical" key in JSON returned by API can be "null" for `[p]covid [country]` command.
Also added new "Recovered Today" field in `[p]covid` command output, because I see the API also returns this data in JSON and I think this would make the covid stats tad more informative.
Please let me know what do you think.
> [Covid] fix for "Critical" + new "Recovered Today" field

- userinfo/userinfo.py
current `bug_hunter_level_2` doesnt exists. *At least, on preda's "emoji" server*
> [Userinfo] Update emojis, part 2

- commandstats/commandstats.py
instead of from commands.converters
> [commandstats] use GuildConverter directly from commands

- embedcreator/embedcreator.py
Trying to create a embed with just a image fails the current detection, it would have been a valid embed, but not pass the detection.
```json
{
"image": {
"url": "https://github.com/Roxedus.png"
},
"color": 7562986,
"type": "rich"
}
```
The JSON is valid, generating the same embed in discord.py and printing the result of to_dict() yields the same JSON.
```py
test_embed = discord.Embed(colour=7562986)
test_embed.set_image(url="https://github.com/Roxedus.png")
js = test_embed.to_dict()
await ctx.send(f"\`\`\`json\n{json.dumps(js)}\`\`\`")
await ctx.send(embed=test_embed)
```
> Fix detection of embed

- commandstats/commandstats.py
This fixes a bug with `[p]cmd guild <guild>` when there can be no data of that target guild in cog's config. You can reproduce it by adding your bot in a new guild and try to fetch cmdstats of that guild or of a guild where no commands have ever been used.
```py
File "/home/ubuntu/merlin/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
File "/home/ubuntu/merlin/cogs/CogManager/cogs/commandstats/commandstats.py", line 176, in guild
data = data[str(server.id)]
KeyError: '213005040934322177'
```
> [CommandStats] bugfix

- antispam/antispam.py
I was having some trouble understanding what the TimedeltaConverter wanted for length before I looked up the code in Red. This change attempts to explain the units to users a bit more.
> [AntiSpam] Update docstrings for better explanation of time

- antispam/antispam.py
There's an extra space in this sentence and since you don't have translations for this cog, I propose stripping the "s" on the units on this message as it's more proper english:
"The spam filter has been set to check commands during a 10 hours period" -> "... during a 10 hour period"
"The spam filter has been set to check commands during a 3 minutes period" -> "... during a 3 minute period"
etc.
> [AntiSpam] Update text on reply

- tips/tips.py
Also uses the cog's formatting when there is no content so messages with only embeds still have formatted tips.
> [tips] do formatting when there's no content

- connect4/connect4.py
Catches when the connect4 message gets deleted/bot loses perms to speak in that channel. Also casts data tracking to a string and uses `start_adding_reactions` so that the game can begin before all reactions are added.
> [connect4] catch message edit errors

- commandstats/commandstats.py
Make [p]cmd guild show the actual guild when id is provided than ctx.guild
> fix small bug in commandstats guild

- forward/forward.py
this command would take a bool option and end up completely ignoring it if passed, resulting in confusing behavior
> [Forward] Respect type when it's passed in `forwardset botmsg`

- snipe/snipe.py
```py
File "/home/main/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
File "/home/main/red/cogs/CogManager/cogs/snipe/snipe.py", line 177, in snipe
description=content[0]
IndexError: list index out of range
The above exception was the direct cause of the following exception:
File "/home/main/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
await ctx.command.invoke(ctx)
File "/home/main/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
await injected(*ctx.args, **ctx.kwargs)
File "/home/main/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped …
```
> Fix snipe continuation when there's no message content

- tips/tips.py
From https://discord.com/channels/240154543684321280/249915052130435074/856935319819124766
This prevents the `Context.send` monkeypatch from raising KeyErrors by using `str.format_map`, and also simplifies its logic.
> [Tips] Fix and simplify monkeypatch

- giveaways/giveaways.py
It appears that [get_partial_message() will always return a PartialMessage, even if the message doesn't exist](https://discordpy.readthedocs.io/en/stable/api.html?highlight=get_partial_message#discord.TextChannel.get_partial_message)
Related Issue: https://sentry.io/share/issue/74c2f00a3f514ef292740bbe684ff93e/
I haven't tested this but it seems like it should work
> [Giveaways] Fix when giveaway message is deleted

- highlight/highlight.py
This will add a new config named `colour`, which defaults to `discord.Color.red().value` (red)
This can be set via `[p]highlightset colour <colour>`
> [Highlight] Feature to set highlight embed colour

- palette/palette.py
This will prevent ValueError if the amount (of colour) provided is 0.
```py
ValueError:  height and width must be > 0
```
> Prevent ValueError if amount < 1

- highlight/highlight.py
Remove the `in {server}` part as discord does that by default now
> [highlight] update the highlight message

- forward/forward.py
this pr fixes 2 thing linked to the fact that recipient is now optional in dpy2:
- When a bot sends a message to a dmchannel, its recipient is None, so we fix that by fetching the channel via its id
- Ephemeral message sent in response to an interaction don't have a guild since their channel is a DMChannel but its id is one of a GuildChannel, so if we fetch it, we'll get a channel that doesn't have a recipient, the way i fixed that is by discarding the message if its fetched channel isn't a DMChannel
This pr was tested without problems with an account that wasn't the bot owner
> [forward] Fix Optional recipient

- userinfo/info.json
- userinfo/userinfo.py
Fixes userinfo throwing an exception due to the changes made [here](https://github.com/Cog-Creators/Red-DiscordBot/commit/10e09d6abcf925544b0ab6965f4cb04b69a30070#diff-8fd2d641da6d7a0358dbc60abe89b5a6f3a8794f6db791e8f9815beb5f3b5614L23-R31)
> [Userinfo] Fix `userinfo` not working on Red 3.5.3

- unbelievaboat/unbelievaboat.py
This PR fixes a edge case which has a 1 in 20 change of hitting.
```py
File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/.local/share/Red-DiscordBot/data/astra/cogs/CogManager/cogs/unbelievaboat/unbelievaboat.py", line 401, in rob
stolen = random.randint(1, int(userbalance * modifier))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/random.py", line 362, in randint
return self.randrange(a, b+1)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/random.py", line 345, in randrange
raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for …
```
> [unbelievaboat] fix a edge case in rob

- palette/converters.py
- palette/info.json
- palette/palette.py
- tiktokreposter/tiktokreposter.py
Here's the hotfix for your palette :p
I removed hexpalette and added it as a parameter for palette instead. I also add detailed parameter to show rgb and hex when passed true.
For the detail, it uses tabulate so I also added that as an extra requirement.
> [Palette] Hotfix
